openapi: 3.1.0
info:
  title: My Development API
  version: v1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development Server
paths:
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: A list of users.
